client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
}

client docker_bridge {
    ipaddr = 192.168.0.0/16
    secret = testing123
}

client all_local {
    require_message_authenticator = true
    ipaddr = 0.0.0.0/0
    secret = testing123
}
